# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username":"admin",
  "password":"123456"
}

###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"disfrutable",
  "rating": 6,
  "movie": {
    "id":1
  },
  "user":{
    "id": 1
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"muy buena pelicula",
  "rating": 8,
  "movie": {
    "id":1
  },
  "user":{
    "id": 2
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"esperaba mas de esta pelicula",
  "rating": 4,
  "movie": {
    "id":2
  },
  "user":{
    "id": 3
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"totalmente decepcionado",
  "rating": 1,
  "movie": {
    "id":2
  },
  "user":{
    "id": 4
  }
}

###

POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"Es la mejor pelicula que vi",
  "rating": 10,
  "movie": {
    "id": 3
  },
  "user":{
    "id": 1
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"pelicula pochoclera, es buena pero no me volo la cabeza",
  "rating": 7,
  "movie": {
    "id": 3
  },
  "user":{
    "id": 2
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"excelente el mensaje que transmite",
  "rating": 8,
  "movie": {
    "id": 4
  },
  "user":{
    "id": 3
  }
}
###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"una pieza clasica del cine",
  "rating": 9,
  "movie": {
    "id": 4
  },
  "user":{
    "id": 4
  }
}

###

PUT http://127.0.0.1:8000/comment/2
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "comment":"muy buena pelicula",
  "rating": 8,
  "movie": {
    "id":1
  },
  "user":{
    "id": 2
  }
}

####

GET http://127.0.0.1:8000/comment/1

####

GET http://127.0.0.1:8000/comment

####

DELETE http://127.0.0.1:8000/comment/1
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

####

GET http://127.0.0.1:8000/comment?movie_id=1